export const SITE_CONFIG = {

  // ── VENUE ──────────────────────────────────────────────
  venueName: "Wilderness Edge Retreat & Conference Centre",
  venueTagline: "Manitoba's premier waterfront venue",
  venueAddress: "32 Burrows Road, Pinawa, MB, Canada",
  venuePhone: "(204) 753-2535",
  venueEmail: "info@wildernessedge.com",
  venueWebsite: "https://wildernessedge.com",
  venueLogo: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHNhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3dce8ddbde5e730be103fc99610f4637a397eb4a/wildernessedge-logo.png",
  heroImageUrl: "https://cdn.prod.website-files.com/64cd635258e0dd2d44ca5585/64f656924da1d90492a10511_64d168dd2b8dffcaee1f7621_Frame20427319192-min-min.webp",

  // ── BUSINESS RULES ─────────────────────────────────────
  groupMinimum: 20, // adults required to unlock meals, meeting rooms

  // ── TAXES (Manitoba) ───────────────────────────────────
  taxes: [
    { name: "GST", rate: 0.05 },
    { name: "PST", rate: 0.07 },
  ],

  // ── GUEST ROOMS ────────────────────────────────────────
  rooms: [
    {
      name: "Standard Room – 1 Queen",
      sku: "standard1queen",
      pricePerNight: 120,
      description: "Charming 1960s-era style with a comfortable queen bed, fridge and built-in desk. Main floor.",
      features: ["Queen bed", "Mini fridge", "Built-in desk", "Main floor"],
      maxQty: 20,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEVCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b67cf39e02d013cfcdc70419486db2a61357c044/Standard-1-queen.webp",
    },
    {
      name: "Standard Room – 2 Doubles",
      sku: "standard2double",
      pricePerNight: 130,
      description: "Two comfortable double beds in our signature 1960s-era décor. Includes fridge and desk.",
      features: ["2 double beds", "Mini fridge", "Built-in desk", "Main floor"],
      maxQty: 20,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbElCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2e1958565b98b212533ac08f6eaf60eec25e3df2/standard-2-double.webp",
    },
    {
      name: "Bachelor Suite",
      sku: "bachelorsuite",
      pricePerNight: 150,
      description: "Spacious and uniquely decorated with a queen log bed and a full kitchenette — microwave, stovetop, fridge and coffee maker.",
      features: ["Queen log bed", "Kitchenette", "Coffee maker", "Unique décor"],
      maxQty: 20,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZFk9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--480f57df787fc1adbc1767e2232f3cddadc782e4/bachelor-left-angle-800.webp",
    },
    {
      name: "Couples Suite",
      sku: "couplessuite",
      pricePerNight: 170,
      description: "Corner window with lake and marina views. Queen log bed, full living room, dining room and kitchen with stove, fridge, coffee maker and pantry.",
      features: ["Lake view", "Queen log bed", "Full kitchen", "Living & dining room"],
      maxQty: 20,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1VCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--15578935d164966f60a3081b3fb1d48e143d4d43/65396ca25445c70e4414ed18_IMG_20231025_131033-p-800.webp",
    },
    {
      name: "Two-Bedroom Suite",
      sku: "twobedroomsuite",
      pricePerNight: 160,
      description: "Two rooms sharing a two-doored bathroom. Each side has a queen bed. Includes mini fridge on one side.",
      features: ["2 queen beds", "Shared bathroom", "Mini fridge", "Ideal for families"],
      maxQty: 20,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazhCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c3ae0fb8a4cd8dca362893a8b3be4541c0216769/two-bedroomsuite-side-1.webp",
    },
    {
      name: "Family Suite",
      sku: "familysuite-nokitchen",
      pricePerNight: 160,
      description: "Two rooms with shared bathroom — one queen bed on one side, three single beds on the other. Mini fridge included.",
      features: ["1 queen + 3 singles", "Shared bathroom", "Mini fridge", "Great for families"],
      maxQty: 20,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHdCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5b19941a5c22f23a413231e622b24bb421f817a5/kids-beds-p-800.webp",
    },
    {
      name: "Kitchen Suite",
      sku: "kitchensuite",
      pricePerNight: 180,
      description: "Two rooms connected through a shared kitchen — one queen and three single beds. Full kitchen with stove, fridge, microwave and coffee maker.",
      features: ["1 queen + 3 singles", "Full kitchen", "Coffee maker", "Connected rooms"],
      maxQty: 20,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2dCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4fdf63f9607f9ea10d47de9bea0a29298124f433/653840edc2fc5d27e647ee7b_65384071a1a71fb9eebd1ae1_IMG_20231024_163828-p-800.webp",
    },
    {
      name: "Accessible Room",
      sku: "handi-suite",
      pricePerNight: 130,
      description: "Fully accessible room on the main floor. Wide 29.5\" entrance door, 35\" bathroom door, 9 grab bars, roll-in shower with chair. Double bed and single bed.",
      features: ["Fully accessible", "Roll-in shower", "Main floor", "Double + single beds"],
      maxQty: 5,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEFCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9e5af6c8840459d3edd5ada5de668121d7570875/handicapp-friendly-room-1.webp",
    },
  ],

  // ── MEETING ROOMS (groups 20+ only) ────────────────────
  meetingRooms: [
    {
      name: "Manitoba Room",
      sku: "manitobaroom",
      pricePerDay: 900,
      description: "Our largest meeting space on the main floor. Ideal for plenary sessions, worship gatherings, large conferences and banquets.",
      features: ["Main floor", "Largest capacity", "AV ready", "Banquet setup available"],
      maxQty: 1,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamxSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7f07e8f02dcff33f9b4eafdefff619d4d1cb62b5/manitoba_room.webp",
    },
    {
      name: "Aggasiz Room",
      sku: "aggasizmeetingrm",
      pricePerDay: 750,
      description: "Large meeting room on the lower level. Excellent for breakout sessions, workshops, or as your main conference hall.",
      features: ["Lower level", "Large capacity", "Breakout-friendly", "Projector available"],
      maxQty: 1,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamhSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--526c03c38467de0149e83b5bfedfab5293c1d6a4/aggasiz_room.webp",
    },
    {
      name: "Whiteshell Room",
      sku: "whiteshell-room",
      pricePerDay: 750,
      description: "Large meeting room on the main floor. Flexible layout ideal for seminars, workshops or overflow seating.",
      features: ["Main floor", "Flexible layout", "Natural light", "Whiteboard included"],
      maxQty: 1,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanhSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4091ddfe796d1f097d36f285d3f6a86224d421ad/pinawa_room.webp",
    },
    {
      name: "Pinawa Room",
      sku: "pinawaroom",
      pricePerDay: 350,
      description: "Mid-size meeting room on the main floor. Perfect for leadership meetings, training sessions or breakout groups.",
      features: ["Main floor", "Mid-size", "TV/display included", "Board table setup"],
      maxQty: 1,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanRSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0c03aa6b2377334c12823d915bb11c963f9d2fc4/pinawa_room.webp",
    },
    {
      name: "McCoy Lounge",
      sku: "mccoy-lounge",
      pricePerDay: 350,
      description: "Relaxed lounge-style meeting space near the dining room. Great for smaller gatherings, receptions or casual breakouts.",
      features: ["Near dining room", "Lounge style", "Relaxed atmosphere", "Reception ready"],
      maxQty: 1,
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanBSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f21a257548aff313b70d00ff27c972c60220e71b/mccoy_room.webp",
    },
  ],

  // ── MEALS (groups 20+ only) ─────────────────────────────
  meals: {
    minimumGuestsForCatering: 20,
    adultBreakfastPrice: 16.50,
    adultLunchPrice: 21.99,
    adultSupperPrice: 23.99,
    nightSnackPrice: 3.00,
    nutritionBreakPrice: 8.00,
    childMealRatePerYear: 1.50,  // per meal = rate × child's avg age
    childNightSnackRate: 0.25,   // per night snack = rate × child's avg age
  },

  // ── ACTIVITIES ─────────────────────────────────────────
  activities: [
    {
      name: "Canoe Rental",
      sku: "canoe-vote",
      price: 17.70,
      unit: "per adult",
      description: "Paddle the scenic Pinawa Channel. Min 2 adults, max 3 people per canoe. Children under 10: $8.85 each.",
      category: "water",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZms9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40b0678c2e1a2adf01da0167ccb5a6b6b5e21b85/64cd635258e0dd2d44ca5bf8_pinawamcitour-105-800.webp",
    },
    {
      name: "River Rafting",
      sku: "raft-vote",
      price: 17.70,
      unit: "per adult",
      description: "A thrilling 1h15m journey down the Pinawa Channel. Up to 6 people per raft. Transport for driver included.",
      category: "water",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZnM9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--761045246dd8963ed716b520c97a6075728a6826/64cd635258e0dd2d44ca5be4_pinawamcitour-20-p-1080.jpeg",
    },
    {
      name: "River Tubing",
      sku: "river-tubing-vote",
      price: 15,
      unit: "per person",
      description: "Pinawa draws up to 4,000 people on a summer weekend for tubing — you have to try it!",
      category: "water",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0VCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c710a76f4dcfba28d6f1868b45655e8c8fbd2045/tubing-wildernesss-edge.webp",
    },
    {
      name: "Hoopla Island Water Park",
      sku: "floating-water-park-vote",
      price: 20,
      unit: "per person",
      description: "Test your \"wipeout\" skills on our giant floating obstacle course. You're guaranteed to get soaked!",
      category: "water",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0FCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--97655e529361231211b51a8a8f3f2945f7100075/Hoopla-action.webp",
    },
    {
      name: "Marina — Kayak / Paddle Board",
      sku: "wilderness-edge-marina",
      price: 20,
      unit: "per person",
      description: "Rent kayaks, canoes and paddleboards at the Wilderness Edge Marina on the Pinawa Channel.",
      category: "water",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVVCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c178369ff51688e2ab31efe20891e1113f09679d/64da7b0b52898a5acba16517_20220801_140027-p-800.webp",
    },
    {
      name: "Island Adventure",
      sku: "island-adventures",
      price: 25,
      unit: "per person",
      description: "Rent a canoe, kayak or paddleboard and head out to an island for a full day of adventures.",
      category: "water",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamtCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5d0c5e8b55523e636131c356c531c97519093135/64f8a6260aa0b663020cab8d_64cd635258e0dd2d44ca5b92_ECP00113-p-800.webp",
    },
    {
      name: "Outdoor Team Building",
      sku: "outdoor-team-building",
      price: 35,
      unit: "per person",
      description: "12-seater canoe excursion, bannock bake, archery, storytelling and more. Perfect for corporate and retreat groups.",
      category: "teambuilding",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGdOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--63d5bbb219c0f0e6b48c77a369e138380b3bc353/outdoor-archery-range.jpg",
    },
    {
      name: "UFO Guided Hike",
      sku: "ufo-guided-hikes",
      price: 15,
      unit: "per person",
      description: "Park Interpreter-led hike along the Falcon Creek Trail with the fascinating story of the 1967 Falcon Lake UFO incident.",
      category: "nature",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXNCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a88f9a546a808f5536b1cd17681ffbcb54ab380f/64f6215d8c23bec07299cff1_64cd635258e0dd2d44ca5bdb_IMG_4352-p-800.webp",
    },
    {
      name: "Owl Prowl Night Hike",
      sku: "owl-prowl-hike",
      price: 15,
      unit: "per person",
      description: "Evening hike to Bear Lake with a Park Interpreter to discover the owls that call the Whiteshell home.",
      category: "nature",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWtCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--38b0c23a82eed8f54806c53e340f9576f6916f54/_64f6172b7d42c85836a9be8a_dominik-van-opdenbosch-lNeIjS1rXus-unsplash-p-800.webp",
    },
    {
      name: "Bannock Point Petroforms",
      sku: "bannock-point-petroforms",
      price: 12,
      unit: "per person",
      description: "Easy 1.9km guided trail near Betula Lake with Indigenous stone petroforms. 35 min. Dogs welcome on leash.",
      category: "nature",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGNCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2a9e2a4095e63809005fa330582d73136c4f4cc1/64f6564332f87d8b032b37e3_64cd635258e0dd2d44ca5bb7_IMG_1567-p-800.webp",
    },
    {
      name: "Swinging Bridge Walk",
      sku: "swinging-bridge-vote",
      price: 10,
      unit: "per person",
      description: "Visit the 50m Pinawa Heritage Suspension Bridge, 4m above the Pinawa Channel. Covered picnic shelter on site.",
      category: "nature",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0lCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ed0458e7222dd591b92d65b9da679d0698276949/64f8a631e7a7af4aebed8d9a_64cd635258e0dd2d44ca5bb2_IMG_1531-p-800.webp",
    },
    {
      name: "Paint Night",
      sku: "paint-night",
      price: 45,
      unit: "per person",
      description: "Guided painting workshop with Madison — Northern Lights, Fall Trees, Grain Elevator and more. All materials provided.",
      category: "creative",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFlCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--89c59ad1a2ee9297a757225402548d83dda70479/64f6569ac304019c72a495d8_64da63ebb4a7dc5b111b2e45_image1201-min.webp",
    },
    {
      name: "Jewelry Making / Craft Workshop",
      sku: "jewelry-making-workshop",
      price: 40,
      unit: "per person",
      description: "Steven & Theresa Frey lead workshops in jewelry making, eco-crafting, wine making, fermenting and campfire storytelling.",
      category: "creative",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbndCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f53d7593dd9b59be9295aea8f4282cd39a4a3ae3/Jewelry%20Making%201.jpg",
    },
    {
      name: "Pool Tables",
      sku: "pool-tables",
      price: 5,
      unit: "per person",
      description: "Premium pool tables available on site for friendly games or tournament-style play.",
      category: "recreation",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzRCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--614a1bd9f7d4f02e48fc112d8b027a44dd0db6b6/Pool-table-area-400.webp",
    },
    {
      name: "Ping Pong",
      sku: "ping-pong",
      price: 5,
      unit: "per person",
      description: "Ping pong tables available on site. Great for all ages.",
      category: "recreation",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzhCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e3444a97e1e7b13bf50952bb3603d318fdaec222/64f8a6575e009783e48893d9_64da6bb80646cf24a6026331_elisey-vavulin-gup-OuACpSs-unsplash-p-500.webp",
    },
    {
      name: "Cross-Country Skiing",
      sku: "cross-country-skiing",
      price: 20,
      unit: "per person",
      description: "40km of classic ski trails in Canadian Shield forest. 12km with skate ski track. 1.2km lit trail.",
      category: "winter",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEVCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b9aef946110ddb78206342598b72794b99235f48/64f8a66bbaca3675f6ee05f9_64da6ff67552cf7bd8f21dad_cross-country-ski-p-500.webp",
    },
    {
      name: "Winter Village",
      sku: "winter-village",
      price: 15,
      unit: "per person",
      description: "Heated tents, fire pits and a collection of mini winter activities. An unforgettable seasonal experience.",
      category: "winter",
      imageUrl: "https://everybooking.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFVCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5969cb6578387c2e8763307f46dd40cac0509668/heated_tent-800.webp",
    },
  ],

  // ── EVENT SEGMENTS ─────────────────────────────────────
  eventSegments: [
    {
      name: "Group Retreat",
      desc: "(Church, Corporate, Youth...)",
      types: [
        "Church / Faith-based",
        "Marriage / Couples",
        "Women's / Ladies'",
        "Men's Retreat",
        "Youth / School",
        "Corporate / Business",
        "Wellness / Personal Growth",
        "Other",
      ],
    },
    {
      name: "Group Conference",
      desc: "(Business, Gov, Non-Profit...)",
      types: [
        "Corporate / Business",
        "Government / Department",
        "Non-Profit Organization",
        "Church / Faith-based",
        "First Nations / Indigenous",
        "College / University",
        "Other",
      ],
    },
    {
      name: "Family Gathering",
      desc: "(Reunion, Holiday, Milestone)",
      types: [
        "Family Reunion",
        "Family Holiday",
        "Milestone Anniversary",
        "Milestone Birthday",
        "Retirement Celebration",
        "Other",
      ],
    },
    {
      name: "Wedding",
      desc: "(Ceremony, Reception, or Both)",
      types: ["Ceremony & Reception", "Ceremony Only", "Reception Only"],
    },
    {
      name: "Individual Guest",
      desc: "(Solo, Couple, Small Group)",
      types: [],
    },
  ],
};
